spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sorimaeul?serverTimezone=Asia/Seoul&useUniCode=yes&characterEncoding=UTF-8
  security:
    oauth2:
      client:
        registration:
          kakao:
            redirect-uri: https://j10e201.p.ssafy.io/login-callback/kakao
          google:
            redirect-uri: https://j10e201.p.ssafy.io/login-callback/google


jwt:
  redis:
    host: localhost