server:
  port: 8000
  servlet:
    context-path: /api


spring:
  # DataBase Settings : hikariCP : https://github.com/brettwooldridge/HikariCP
  datasource:
    url: ENC(PmNLzkIntvtI13MnbMrp0EGR4XWwLaXFg4pyF9/rgK++oRs/DVLyD7zxssTdNIHxK963gst9/1shqurZu0+RzZHZfSBE5vhXAKVfF2B3cFvU+q6LG+HYWuCQ7A5zDGKdJD0egPDgb1/+3Dy3ph9O7Q==)
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ENC(6D5UHgUn8PlWmRpNCLfvPg==)
    password: ENC(HchKvSrfF8OBFm/PILKNjD+EfHY5+hPi)
    pool-name: Hikari Connection Pool
    # hikariCP property setting
    maximum-pool-size: 10
    connection-timeout: 5000
    connection-init-sql: SELECT 1
    idle-timeout: 600000
    max-lifetime: 1800000
    auto-commit: true
  security:
    user:
      name: admin
      password: admin
    # OAuth 설정
    oauth2:
      client:
        registration:
          kakao:
            client-id: ENC(EJ8R1u3WY1/eiBujSWUlblHBbl5VFKiv5gXbj3/jW6XD6lD/2bToFgwIDRogBCrb)
            client-secret: ENC(1v20Lih3Z5U+RWLNzTZs7c+dzbumLWoTxFcXfsrg/p5ggRN/FK17dfIGjHMMb9X1)
            redirect-uri: ENC(oKcA9YF7w470WY85J0p9ZC9TY2voUSOoKytSyKYso8hOXgztnoHPIxbn+CupGIfLQNy36sloAfo=)
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            client_name: kakao
          google:
            client-id: ENC(DdZKFBof+WHnQmwtGFwGPh2YI37ny9HAmjl05JgJIgsqrwmcZDhGwopw7kkgzPmmMXidTFxniStRwPnf7ZuXTxpThtN35EsAGyC8f2ADNbfAxyhDDVZPxw==)
            client-secret: ENC(kqrGdtIp2XQURxr9qQrdVBsi75M2pPLK7Ur0+6iCFmNwvQHJg5Ma99Fpzo/FM51T)
            redirect-uri: ENC(hhbgr30JoQvlb20FlOXkt8MoN+LQKQ39IGVZohemt+/PH0EayLZvGP+sipmBvRCEokIAiM9gLv/psCThU1SXCw==)
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
  jpa:
    open-in-view: false


jwt:
  token:
    secret-key: ENC(p9Yv00Nggrip5TR3DvDckg2vyWmTVOo78dD+6g8ME/SJBdv6sGwo9pP0xvU1jZrleDx5Ip26uxTYoB+aHXbi9r1eFkq4teuwYYAbgiAIrRE=)
  access-token:
    expire-length: 1800000
  refresh-token:
    expire-length: 1209600000
  redis:
    host: localhost
    port: 6379
    password: ENC(fbVzkxQrgWvOBja+l//F2trn+HeA7ekU)


# Multipart File Upload Setting
file:
  multipart:
    maxUploadSize: 1000000
    maxUploadSizePerFile: 1000000


## Swagger setting
springdoc:
  packages-to-scan: com.usagi.sorimaeul.api.controller
  swagger-ui:
    path: /api-docs
    groups-order: DESC
    tags-sorter: alpha
    operations-sorter: alpha
    disabled-swagger-default-url: true
    display-request-duration: true
  api-docs:
    path: /api-docs/json
    groups:
      enabled: true
  show-actuator: true
  cache:
    disabled: true
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8


# log level Setting
logging:
  level:
    root: info
    org:
      springframework:
        root: debug
        web: debug
    com:
      sorimaeul: debug
    zaxxer:
      hikari:
        pool:
          HikariPool: debug

# S3 Bucket
cloud:
  aws:
    s3:
      bucket: ENC(qLX/RiwHx0Ef9X9zUIjVVVEgKBNDBn2N)
    region:
      static: ENC(axFWnpgpOVL8nKkRkXhqWPPnqRpVfrbd)
    credentials:
      access-key: ENC(HIq7IcwId5myQ/2gPhvGjqgI8Obvf2x8cmPnE2Yhj2Q=)
      secret-key: ENC(3J0px/WljbwFjoLuCUricjoXUWSipL9a9n8YoiipM0eZ7ZeDal9TYPYAO07uOTTTcWFgl1BUUjY=)
    stack:
      auto: false
