spring:
  datasource:
    url: jdbc:mysql://j10e201.p.ssafy.io:3306/sorimaeul?serverTimezone=Asia/Seoul&useUniCode=yes&characterEncoding=UTF-8
  security:
    oauth2:
      client:
        registration:
          kakao:
            redirect-uri: http://localhost:3000/login-callback/kakao
          google:
            redirect-uri: http://localhost:3000/login-callback/google


jwt:
  redis:
    host: j10e201.p.ssafy.io


jasypt:
  encryptor:
    password: usagi